# Generated by Django 5.0.7 on 2024-07-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='seats',
        ),
        migrations.AddField(
            model_name='airline',
            name='capacity',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='seats_used',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
