# Generated by Django 5.0.7 on 2024-07-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_airline_image_alter_airline_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderflight',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='orderflight',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
