# Generated by Django 5.0.7 on 2024-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_rename_user_customer_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='seats_used',
            field=models.IntegerField(blank=True, max_length=240, null=True),
        ),
    ]
