# Generated by Django 5.0.7 on 2024-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_alter_airline_seats_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='seats_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
