# Generated by Django 5.0.7 on 2024-07-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_customer_state_orderflight_totalbill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderflight',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
