# Generated by Django 5.0.7 on 2024-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_orderflight_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='available_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
